spring.application.name=officeManagment
server.port=8080

# Enable H2 Database Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Database Connection Settings (added DB_CLOSE_DELAY to keep memory alive)
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate / JPA Settings
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true